# Generated by Django 6.0.7 on 2026-08-14 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('archetype', models.CharField(blank=True, max_length=150)),
                ('era', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('worldview', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('speech_style', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=list)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('quirks', models.JSONField(blank=True, default=list)),
                ('markdown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('personality', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='agent_os.personality')),
            ],
        ),
    ]
